// Fallback values for every setting in site.js. You don't need to edit this file:
// anything left out of site.js gets the value here.

const defaults = {
  name: 'Lab',
  shortName: null,
  tagline: '',
  description: '',
  institution: null,
  url: '',
  favicon: 'favicon.svg',
  faviconBackground: '#ffffff',
  ogImage: null,
  socialImages: true,
  locale: 'en-US',
  theme: {
    accent: '#2563eb',
    accentDark: null,
    defaultMode: 'system',
    font: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  router: 'browser',
  header: { logo: null, showName: true, showModeToggle: true, showSearch: true },
  analytics: {
    plausible: { domain: '', src: 'https://plausible.io/js/script.js' },
    umami: { websiteId: '', src: 'https://cloud.umami.is/script.js' },
    googleAnalytics: '',
    cookieConsent: true,
    consentText: 'This site uses cookies from Google Analytics to count visits.',
  },
  nav: [],
  home: {
    sections: ['slider', 'intro', 'notices', 'hiring', 'news', 'events', 'research', 'publications', 'funders'],
    slider: { autoplay: true, interval: 6000, progress: true, aspectRatio: '21 / 9', mobileAspectRatio: '4 / 3' },
    intro: { heading: null, text: [], image: null, imageAlt: '', imageCaption: '', imagePosition: 'below' },
    news: { title: 'News', count: 4, moreLink: 'All news' },
    research: { title: 'Research', count: 4, moreLink: 'All projects' },
    publications: { title: 'Selected publications', count: 3, moreLink: 'All publications', showSummary: true },
    events: { title: 'Upcoming events', count: 3, moreLink: 'All events' },
    funders: { title: 'Funding', count: 8 },
    notices: { count: 3 },
    hiring: { text: null, linkLabel: 'See open positions' },
    talks: { title: 'Recent talks', count: 3, moreLink: 'All talks' },
  },
  research: {
    title: 'Research',
    intro: null,
    sections: ['current', 'past'],
    currentTitle: 'Current projects',
    pastTitle: 'Past projects',
    showTags: true,
    project: {
      sections: ['description', 'funding', 'links', 'people', 'publications'],
      peopleTitle: 'People',
      publicationsTitle: 'Publications',
    },
  },
  people: {
    title: 'People',
    intro: null,
    sections: ['members', 'alumni'],
    groups: [],
    management: { show: false, title: 'Management team', after: null },
    alumniTitle: 'Alumni',
    showPhotos: true,
    highlightInAuthorLists: true,
    profile: {
      sections: ['links', 'bio', 'interests', 'education', 'projects', 'publications', 'talks', 'awards'],
      interestsTitle: 'Interests',
      educationTitle: 'Education',
      projectsTitle: 'Projects',
      publicationsTitle: 'Publications',
      talksTitle: 'Talks',
      awardsTitle: 'Awards',
    },
  },
  publications: {
    title: 'Publications',
    intro: null,
    scholarUrl: null,
    filters: ['search', 'type', 'year', 'author', 'tag'],
    authorFilter: 'members',
    groupByYear: true,
    showCount: true,
    showDownload: true,
    showBibtex: true,
    showAbstract: true,
    import: { bibtex: 'publications.bib', orcid: [], dblp: [], semanticScholar: [], googleScholar: [], exclude: [] },
    pages: true,
    page: { sections: ['media', 'links', 'summary', 'abstract', 'cite', 'related'] },
    citations: { show: true, label: 'Cited by' },
    chart: { show: true, profiles: true, minYears: 3, title: 'Publications per year' },
    summaryTitle: 'In brief',
    media: { show: true, position: 'right', width: '13rem', aspect: '16 / 10' },
    types: {
      journal: 'Journal',
      conference: 'Conference',
      workshop: 'Workshop',
      preprint: 'Preprint',
      book: 'Book / Chapter',
      thesis: 'Thesis',
      other: 'Other',
    },
  },
  news: { title: 'News', intro: null, groupByYear: true, rss: true, readMore: 'Read more' },
  newsletter: {
    provider: null,
    buttondown: '',
    action: '',
    emailField: 'email',
    title: 'Get our news by email',
    text: 'New posts from the lab in your inbox. Unsubscribe any time.',
    button: 'Subscribe',
    placement: ['news', 'post'],
  },
  talks: {
    title: 'Talks',
    intro: null,
    groupByYear: true,
    types: {
      keynote: 'Keynote',
      invited: 'Invited talk',
      contributed: 'Contributed talk',
      tutorial: 'Tutorial',
      lecture: 'Lecture',
      panel: 'Panel',
      poster: 'Poster',
      other: 'Talk',
    },
  },
  press: {
    title: 'Awards & press',
    intro: null,
    sections: ['awards', 'press'],
    awardsTitle: 'Awards',
    pressTitle: 'In the media',
  },
  collaborators: {
    title: 'Collaborators',
    intro: null,
    sections: ['map', 'list'],
    showLab: true,
  },
  events: {
    title: 'Events',
    intro: null,
    sections: ['upcoming', 'past'],
    upcomingTitle: 'Upcoming',
    pastTitle: 'Past events',
    timezone: 'UTC',
    showSubscribe: true,
    calendarLinks: true,
    media: { show: true, position: 'right', width: '11rem', aspect: '16 / 10' },
  },
  gallery: { title: 'Gallery', intro: null },
  resources: {
    title: 'Software & Data',
    intro: null,
    sections: ['software', 'dataset', 'other'],
    sectionTitles: { software: 'Software', dataset: 'Datasets', other: 'Other' },
    github: true,
  },
  teaching: { title: 'Teaching', intro: null, showInstructor: true, showDescription: true },
  join: {
    title: 'Join the lab',
    sections: ['intro', 'positions', 'apply'],
    positionsTitle: 'Positions',
    applyTitle: 'How to apply',
    showClosedPositions: true,
  },
  contact: {
    title: 'Contact',
    intro: null,
    sections: ['email', 'phone', 'address', 'directions', 'map', 'form'],
    email: null,
    phone: null,
    address: [],
    directions: null,
    map: { lat: null, lng: null, zoom: 16, provider: 'google', embedUrl: null, showLinks: true },
    form: {
      provider: null,
      formspreeId: '',
      web3formsKey: '',
      title: 'Send us a message',
      success: 'Thanks, your message was sent. We will get back to you soon.',
    },
  },
  linkCheck: { enabled: true, ignore: [] },
  footer: {
    show: true,
    sections: ['copyright', 'institution', 'social', 'credit'],
    text: '',
    social: [],
    // The template author's credit; see "Footer credit" in README.md.
    credit: {
      text: 'Built with',
      by: 'by',
      name: 'Kiarash',
      url: 'https://kiarashs.ir',
      avatar: 'https://avatars.githubusercontent.com/u/1054134?s=96',
    },
  },
}

export default defaults
