// Fallback values for every setting in site.js. You don't need to edit this file:
// anything left out of site.js gets the value here.

const defaults = {
  name: 'Lab',
  shortName: null,
  tagline: '',
  description: '',
  institution: null,
  url: '',
  favicon: 'favicon.svg',
  ogImage: null,
  socialImages: true,
  locale: 'en-US',
  theme: {
    accent: '#2563eb',
    accentDark: null,
    defaultMode: 'system',
    font: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  router: 'browser',
  header: { logo: null, showName: true, showModeToggle: true, showSearch: true },
  analytics: {
    plausible: { domain: '', src: 'https://plausible.io/js/script.js' },
    umami: { websiteId: '', src: 'https://cloud.umami.is/script.js' },
    googleAnalytics: '',
    cookieConsent: true,
    consentText: 'This site uses cookies from Google Analytics to count visits.',
  },
  nav: [],
  home: {
    sections: ['slider', 'intro', 'hiring', 'news', 'events', 'research', 'publications', 'funders'],
    slider: { autoplay: true, interval: 6000, aspectRatio: '21 / 9' },
    intro: { heading: null, text: [], image: null, imageCaption: '' },
    news: { title: 'News', count: 4, moreLink: 'All news' },
    research: { title: 'Research', count: null, moreLink: 'All projects' },
    publications: { title: 'Selected publications', count: null, moreLink: 'All publications' },
    events: { title: 'Upcoming events', count: 3, moreLink: 'All events' },
    funders: { title: 'Funding' },
    hiring: { text: null, linkLabel: 'See open positions' },
  },
  research: {
    title: 'Research',
    intro: null,
    sections: ['current', 'past'],
    currentTitle: 'Current projects',
    pastTitle: 'Past projects',
    showTags: true,
    project: {
      sections: ['description', 'funding', 'links', 'people', 'publications'],
      peopleTitle: 'People',
      publicationsTitle: 'Publications',
    },
  },
  people: {
    title: 'People',
    intro: null,
    sections: ['members', 'alumni'],
    groups: [],
    management: { show: false, title: 'Management team', after: null },
    alumniTitle: 'Alumni',
    showPhotos: true,
    highlightInAuthorLists: true,
    profile: {
      sections: ['links', 'bio', 'interests', 'education', 'projects', 'publications'],
      interestsTitle: 'Interests',
      educationTitle: 'Education',
      projectsTitle: 'Projects',
      publicationsTitle: 'Publications',
    },
  },
  publications: {
    title: 'Publications',
    intro: null,
    scholarUrl: null,
    filters: ['search', 'type', 'year', 'author', 'tag'],
    authorFilter: 'members',
    groupByYear: true,
    showCount: true,
    showDownload: true,
    showBibtex: true,
    showAbstract: true,
    import: { bibtex: 'publications.bib', orcid: [] },
    pages: true,
    citations: { show: true, label: 'Cited by' },
    types: {
      journal: 'Journal',
      conference: 'Conference',
      workshop: 'Workshop',
      preprint: 'Preprint',
      book: 'Book / Chapter',
      thesis: 'Thesis',
      other: 'Other',
    },
  },
  news: { title: 'News', intro: null, groupByYear: true, rss: true, readMore: 'Read more' },
  events: {
    title: 'Events',
    intro: null,
    sections: ['upcoming', 'past'],
    upcomingTitle: 'Upcoming',
    pastTitle: 'Past events',
    timezone: 'UTC',
    showSubscribe: true,
  },
  gallery: { title: 'Gallery', intro: null },
  resources: {
    title: 'Software & Data',
    intro: null,
    sections: ['software', 'dataset', 'other'],
    sectionTitles: { software: 'Software', dataset: 'Datasets', other: 'Other' },
  },
  teaching: { title: 'Teaching', intro: null, showInstructor: true, showDescription: true },
  join: {
    title: 'Join the lab',
    sections: ['intro', 'positions', 'apply'],
    positionsTitle: 'Positions',
    applyTitle: 'How to apply',
    showClosedPositions: true,
  },
  contact: {
    title: 'Contact',
    intro: null,
    sections: ['email', 'phone', 'address', 'directions', 'map', 'form'],
    email: null,
    phone: null,
    address: [],
    directions: null,
    map: { lat: null, lng: null, zoom: 16, provider: 'google', embedUrl: null, showLinks: true },
    form: {
      provider: null,
      formspreeId: '',
      web3formsKey: '',
      title: 'Send us a message',
      success: 'Thanks, your message was sent. We will get back to you soon.',
    },
  },
  footer: { show: true, sections: ['copyright', 'institution', 'social'], text: '', social: [] },
}

export default defaults
